package com.venscor.demo.entity;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.name
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.addr
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.age
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.sex
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.name
     *
     * @return the value of task.name
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.name
     *
     * @param name the value for task.name
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.addr
     *
     * @return the value of task.addr
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.addr
     *
     * @param addr the value for task.addr
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.age
     *
     * @return the value of task.age
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.age
     *
     * @param age the value for task.age
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.sex
     *
     * @return the value of task.sex
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.sex
     *
     * @param sex the value for task.sex
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}