package com.venscor.demo.dao;

import com.venscor.demo.entity.Task;
import com.venscor.demo.entity.TaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    long countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    @Delete({
        "delete from task",
        "where name = #{name,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    @Insert({
        "insert into task (name, addr, age, ",
        "sex)",
        "values (#{name,jdbcType=CHAR}, #{addr,jdbcType=CHAR}, #{age,jdbcType=CHAR}, ",
        "#{sex,jdbcType=CHAR})"
    })
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    @Select({
        "select",
        "name, addr, age, sex",
        "from task",
        "where name = #{name,jdbcType=CHAR}"
    })
    @ResultMap("com.venscor.demo.dao.TaskMapper.BaseResultMap")
    Task selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    int updateByExample(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Dec 23 21:13:24 CST 2019
     */
    @Update({
        "update task",
        "set addr = #{addr,jdbcType=CHAR},",
          "age = #{age,jdbcType=CHAR},",
          "sex = #{sex,jdbcType=CHAR}",
        "where name = #{name,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(Task record);
}